#!/usr/bin/env python

import argparse
from ace import commands

parser = argparse.ArgumentParser()

parser.add_argument('command')
parser.add_argument('--library-key',dest='library_key',default=None)
parser.add_argument('--api-key',dest='api_key',default=None)
parser.add_argument('--project',dest='project',default=None)
parser.add_argument('--endpoint',dest='endpoint',default='https://www.axilent.net')
parser.add_argument('--api-version',dest='api_version',default='astoria-preview') # TODO needs to change once astoria is released
parser.add_argument('--data-file',dest='data_file',default=None)
parser.add_argument('--graphstack',dest='graphstack',default=None)
parser.add_argument('--category',dest='category',default=None)
parser.add_argument('--action',dest='action',default=None)
parser.add_argument('--num-triggers',dest='num_triggers',default=1)
parser.add_argument('--profile-distribution',dest='profile_distribution',default=1.0) # percent of triggers with unique profile ids
parser.add_argument('--variables',dest='variables',default=None) # trigger variables with pattern var1:val1,var2:val2,var3:val3...
parser.add_argument('--profile',dest='profile',default=None) # you can specify a particular profile

def usage(args):
    print 'Usage: ace <command>'

def main():
    """
    Mainline.
    """
    args = parser.parse_args()
    try:
        command = getattr(commands,args.command)
        command(args)
    except AttributeError:
        usage(args)

if __name__ == '__main__':
    main()

