#!/usr/bin/env python

import argparse
from ace import core
from ace import plugins

parser = argparse.ArgumentParser()

parser.add_argument('command')
parser.add_argument('subcommand',nargs='?',default='__default__')
parser.add_argument('--endpoint',dest='endpoint',default='https://www.axilent.net') # for debugging

core.seed_parser(parser)
#plugins.seed_parser(parser)

commands = {}
core.seed_commands(commands)
#plugins.seed_commands(commands)

help = {}
core.seed_help(help)
#plugins.seed_help(help)

def usage(args):
    print 'Usage: ace <command> <subcommand>'

def do_help(args):
    """ 
    Gets help.
    """
    try:
        help_message = help[args.command][args.subcommand]
        print help_message
    except KeyError:
        usage(args)

def main():
    """
    Mainline.
    """
    args = parser.parse_args()
    # if args.help:
    #     do_help(args)
    # else:
    try:
        com = commands[args.command][args.subcommand]
        com(args)
    except KeyError:
        usage(args)

if __name__ == '__main__':
    main()

